### ISSUE TITLE
Does not work because of mustache dependency

### ISSUE THREAD

**Issue by tkbky** [terry90/rails_api_benchmark#1]
I'm getting the error `Cannot load such file -- mustache (LoadError)` when trying to run `rails g rails_api_benchmark:config`. Did a quick search on the code base, found that it is `require 'mustache'` in several places, but `mustache` was removed from the dependency.

**Comment by terry90** [comment]
Sorry, I do not have time to look into this for now, but I will gladly accept a PR.
I may do it next week

**Comment by terry90** [comment]
I released a new version with mustache included
